# Generated by Django 2.2 on 2020-09-12 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('enterTime', models.DateTimeField(auto_now_add=True, verbose_name='入职时间')),
                ('leaveTime', models.DateTimeField(auto_now=True, verbose_name='离职时间')),
                ('iphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='住址')),
                ('departments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyInfo.Department', verbose_name='部门')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companyInfo.Position', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'LCMS_user',
            },
        ),
    ]
