# Generated by Django 2.2 on 2020-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enterTime',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaveTime',
            field=models.DateTimeField(verbose_name='离职时间'),
        ),
    ]
