# Generated by Django 2.2 on 2020-09-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200912_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enterTime',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaveTime',
            field=models.DateField(verbose_name='离职时间'),
        ),
    ]
