# Generated by Django 2.2 on 2020-10-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('company_register', models.CharField(max_length=20, verbose_name='公司法人')),
                ('business_license', models.CharField(max_length=50, verbose_name='营业执照')),
                ('register_money', models.CharField(max_length=20, verbose_name='注册资金')),
                ('company_address', models.CharField(max_length=50, verbose_name='公司地址')),
                ('company_detail', models.CharField(max_length=1000, verbose_name='公司详情')),
            ],
            options={
                'verbose_name': '公司详情',
                'verbose_name_plural': '公司详情',
                'db_table': 'LCMS_companydetail',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=11, verbose_name='编号')),
                ('label', models.CharField(max_length=50, verbose_name='标签')),
                ('department', models.CharField(max_length=20, verbose_name='部门名称')),
                ('department_people', models.CharField(max_length=200, verbose_name='部门人数')),
                ('create_time', models.DateField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '部门信息',
                'verbose_name_plural': '部门信息',
                'db_table': 'LCMS_companystructure',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=15, verbose_name='岗位')),
            ],
            options={
                'verbose_name': '岗位信息',
                'verbose_name_plural': '岗位信息',
                'db_table': 'LCMS_position',
            },
        ),
    ]
